### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by avadhbsd** [Present-Inc/CardStackViewController#1]
<img width="1440" alt="screen shot 2017-05-27 at 8 29 17 pm" src="https://cloud.githubusercontent.com/assets/549567/26522819/a79ea710-4326-11e7-941b-d97a6fce9408.png">
Hey, I have downloaded it and tried fixing the syntax for swift 3;

But it does not seem to work; some Override from extension error did not let it run. Though I fixed other.

I would truly appreciate if you could please give it a shot and see if it can play nice with Swift 3. 

Looking forward to it.

Thanks so much for helping.

**Comment by justinmakaila** [comment]
Hey @avadhbsd, this project is not currently maintained. It'd be up to you to get the Swift 3 support working, we haven't supported or touched this project in a few years. Thanks!

**Comment by avadhbsd** [comment]
So I was able to fix it with the help from @naturaln0va he has been generous enough to donate his time and help me solve the issues.

@naturaln0va Thanks so much bro. Can not thank you enough. Truly appreciate this.
